---
- name: "Make some backend directories of application"
  file:
    path: ~/backend-app
    state: directory

- name: "Create Unarchived files for the backend"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Create the dependency node"
  shell: |
    cd ~/backend-app
    npm i
- name: "Execute node app using the PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Start to build the pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu